### ISSUE TITLE
Support glob patterns in CLI flags

### ISSUE THREAD

**Issue by h2non** [mrak/stubby4node#29]
It could be really useful introduce support for [glob](https://github.com/isaacs/node-glob) pattern expressions to do something like:

```bash
stubby -d test/fixtures/**/*.{yaml,json}
```

**Comment by mrak** [comment]
I've been thinking on this, too. It might make the most sense to remove the `-d,--data` flag and simply accept any number of files as the command's arguments. Existing flags would be unchanged

**Comment by h2non** [comment]
That will be great! May be I could have time this weekend provide support for it :D

**Comment by mrak** [comment]
For the meantime you can try `cat` and shell process substitution:

```
stubby -d <(cat data/**/*.{yaml,json})
```

I'll warn you ahead of time that this may break if you use the `-w,--watch` flag

**Comment by mrak** [comment]
@h2non did using `cat` work for you?

**Comment by h2non** [comment]
Yeah! Closing
