### ISSUE TITLE
Should be able to re-stub using the same endpoint without restarting Stubby

### ISSUE THREAD

**Issue by murphyj** [mrak/stubby4node#32]
It seems like a useful feature that you might want to POST/PUT new content to replace old content in Stubby.

The reason for this is that the data might change for an endpoint so we want to cucumber test that the logic retrieving our mocked out data behaves as expected. If we take a real world example, let's say that you have a queue that contains a message or subscription which means in turn that it regularly polls an endpoint (stubby our stub service in our tests) for some data. If say the data returned by stubby changes then the behaviour changes.

Is this something that Stubby should support?

**Comment by murphyj** [comment]
I just realised **head-smack moment** that you can just use `DELETE` but it seems like you should just be able to re-`POST` as that makes more sense to me than a `POST-DELETE-POST`

**Comment by mrak** [comment]
You can :)

You can either do a PUT request through the admin portal or use the programmatic API to `put()` and replace an existing endpoint
