### ISSUE TITLE
Unexpected error, when matching query with duplicate parameters

### ISSUE THREAD

**Issue by perezlatino** [mrak/stubby4node#35]
Hi there,

The following url  stubby/question?sectionIds[]=40022&sectionIds[]=40023
throws an unexpected error

17:49:22 -> GET [stubs]/stubby/question?sectionIds[]=40022&sectionIds[]=40023
17:49:22 <- 500 [stubs]/stubby/question?sectionIds[]=40022&sectionIds[]=40023 unexpectedly generated a server error: Object 40022,40023 has no method 'match'

That is because the sectionIds param resolves into an array value [40022, 40023], so when calling the method endpoint.js#matchRegex it brakes because [40022, 40023].match is not supported

This is the function
  matchRegex = function(compileMe, testMe) {
    if (testMe == null) {
      testMe = '';
    }
    return testMe.match(RegExp(compileMe, 'm'));
  };

Thanks

**Comment by mrak** [comment]
Could you provide me with the endpoint you have configured in your `YAML` along with the full request you are making?

I have to admit I did not take this scenario into account before (it's a perfectly valid scenario, too)

I'll reproduce your scenario and work on a fix. Handling multi-value query parameters is not standardized across web frameworks, so I'll need to find something that makes sense despite the web stack's implementation.

**Comment by perezlatino** [comment]
Thanks Eric,

This is the url
/stubby/question?sectionIds[]=40022&sectionIds[]=40023

Configuration
    {
        "request": {
            "url": "^/stubby/question",
            "query": {
                "sectionIds[]": ["40022","40027", "40031"]
            },
            "method": "GET"
        },
        "response": {
            "status": 200,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*"
            },
            "body": "File not found",
            "file": "app/tests/fixtures/sections_response.json"
        }
    },

**Comment by mrak** [comment]
Were you expecting a `404` here? I see that not all of the `sectionIds` have been specified in the url you hit

**Comment by perezlatino** [comment]
No, the url is wrong, it should have all ids

**Comment by mrak** [comment]
Should be fixed by #44. See the README for details about matches repeated query string keys
