### ISSUE TITLE
soap envelopes

### ISSUE THREAD

**Issue by alex-moreno** [mrak/stubby4node#38]
Is it possible to create SOAP envelopes to emulate a SOAP server interaction?

Cheers.

**Comment by mrak** [comment]
You could write the SOAP envelopes in the `post`, `body` or `file` values. This library will only match on regex or direct string equality though

**Comment by alex-moreno** [comment]
so, I guess both post or file should match exactly what the request would be in order to answer the request of the client.

Thank you.

**Comment by mrak** [comment]
You can use regular expressions, too

**Comment by alex-moreno** [comment]
Just for the sake of documentation, the regex worked like a charm. Tried to match against the whole request using file, but didn't work, so tried something like:


- request:
    url: /my-enpoint
    method: POST
    # TODO: Write some regex more sophisticated than that.
    post: .*A-NUMBER-TO-TRACK-IN-THE-REQUEST.*
    file:
  response:
    status: 200
    file: response/numbers/number-to-track.soap.xml

Thanks :-)
