### ISSUE TITLE
Add JSON comprehension

### ISSUE THREAD

**Issue by jj4th** [mrak/stubby4node#53]
For RESTful APIs, it's important to be able to specify stubbed request bodies as JSON strings.  JSON does not require the key/value pairs to be in any particular order, and in fact browsers and applications may provide the same JSON object with different serialized strings.

This issue proposes a new JSON stringified object member on the request object: `request.json` that when provided, will compare against the incoming `post` body by attempting to parse the `post` data as JSON and perform a deeply equal test.

**Comment by tomreece** [comment]
+1
