### ISSUE TITLE
Option to disable colorised output

### ISSUE THREAD

**Issue by mikeparker** [mrak/stubby4node#58]
I hope I have the right repository - please let me know if not.

We're using stubby via npm in a docker image and have a log parser listening to the docker container output. However, it trips up on colorised output. 

I think I'm right in saying there is no option for monochrome output? It would be great to provide simple plain text output.

**Comment by mrak** [comment]
There isn't an option to explicitly disable colorized output, but stubby should only be outputting colors if it detects that STDOUT is a TTY.

Is your setup running the stubby instance on an allocated pseudoterminal?
