### ISSUE TITLE
Option to set a limit of requests allowed

### ISSUE THREAD

**Issue by michalstocki** [mrak/stubby4node#60]
I want to write a test which proves that my client is performing requests optimally. Especially I don't want my client to call multiple times for the same resource.

It would be great to have an option to limit number of allowed calls for a particular endpoint or have an option to get from the Admin Panel info about call count by the given endpoint id.

**Comment by mrak** [comment]
Being able to see the amount of times an endpoint has been called is a great idea. That value is already tracked internally and shouldn't be too hard to surface.

**Comment by mrak** [comment]
Version `4.0.0` has now been released. It includes a `hits` value that is returned from the admin endpoint and in the admin panel.

```yaml
{
  request: {}
  response: {}
  hits: 0
  id: 1
}
```

**Comment by michalstocki** [comment]
Thanks a lot!
