### ISSUE TITLE
Log incoming/outgoing requests

### ISSUE THREAD

**Issue by ValeryIvanov** [mrak/stubby4node#61]
Hi!

First of all, very good server, using it every day in my development, thanks!

Is it possible to add a toggle to log incoming and or outgoing requests to console?
This would make easier to debug of what kind of requests my app is making to one particular endpoint and then configure responses for them.

Thanks!

**Comment by mrak** [comment]
I'm glad you are finding stubby useful!

As for logging requests, there are existing tools in the ecosystem for recording HTTP requests and responses. Something like `JMeter` could work?
