### ISSUE TITLE
Feature request: need to add current-time to the template file

### ISSUE THREAD

**Issue by bahram-dazn** [mrak/stubby4node#76]
I need to add current time to a response template that have similar to adding query and header string using <% ...%> as described the README (Templating body and file).
This for example might be taken from the actual requests timestamp if there is a way of accessing it.

**Comment by bahram-dazn** [comment]
Sorry, I think I can do this using just JS code in the template!

**Comment by mrak** [comment]
Glad you found a way for your use-case!
